#!/bin/bash


languages=(
    openjdk-8-jre-headless
)

programs=(
    tree
    neovim
    git
    stow
    zsh
    tmux
)

dont_stow=(
    install
    )

install_languages() {
    for language in "${languages[@]}"; do
        sudo apt install "$language" -y
    done
}

install_apt_snap_programs() {
    for apt_program in "${programs[@]}"; do
        sudo apt install "$apt_program" -y
    done
}

stow_directories() {
    ls ~/Dotfiles | while read stowdir; do
        for dont_stow_file in "${dont_stow[@]}"; do
            if [ $stowdir != $dont_stow_file ]; then
                stow $stowdir && echo "stowed $stowdir"
            fi
        done
    done
}

install_languages
install_apt_snap_programs
stow_directories

chsh -s "$(which zsh)"

echo "----------------RESTART TO FINISH INSTALLATION-----------------------"


