#!/bin/bash
apt_programs=(
    xprop
    tlp
    inotify-tools
    emacs
    hsetroot
    xdotool
    neovim
    git
    stow
    bspwm
    sxhkd
    dunst
    dmenu
    lemonbar
    ranger
    sxiv
    zathura
    zsh
    slock
    chromium-browser
    flameshot
    fzf
    acpi
    xcompmgr
    libxft-dev
    #brightnessctl
)
    #sudo snap install code --classic

sudo tlp start

for apt_program in "${apt_programs[@]}"; do
    sudo apt install "$apt_program" 
done

# stow everything except install.sh and system_scripts regularly.
# do sudo stow --target=/ system_scripts for system_scripts folder to stow in /usr/bin
ls | while read stowdir; do
	if [ ! -z "$(echo $stowdir | grep system_scripts)" ]; then continue; fi
	if [ ! -z "$(echo $stowdir | grep install)" ]; then continue; fi
	stow $stowdir && echo "stowed $stowdir"
done

sudo stow --target=/ system_scripts

# install tabbed and st
cd ~/.config/tabbed
sudo make clean install
cd ~/.config/st
sudo make clean install

# install fzf, move .fzf.zsh to .config/zsh
cd ~/.config/fzf
./install --no-bash --no-fish
mv ~/.fzf.zsh ~/.config/zsh/

chsh -s "$(which zsh)"

# install source code pro
#set  -euo pipefail
#I1FS=$'\n\t'
#mkdir -p /tmp/adodefont
#cd /tmp/adodefont
#wget -q --show-progress -O source-code-pro.zip https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
#unzip -q source-code-pro.zip -d source-code-pro
#mkdir -p ~/.fonts
#cp -v source-code-pro/*/OTF/*.otf ~/usr/local/share/fonts/
#fc-cache -f
#rm -rf source-code-pro{,.zip}

#install inconsolata font
sudo apt-get install fonts-inconsolata -y
sudo fc-cache -fv

# remove sudo permissions on keyboard and laptop brightnesss
sudo chmod o+w /sys/class/leds/kbd_backlight/brightness
sudo chmod o+w /sys/class/backlight/intel_backlight/brightness

echo "----------------RESTART TO FINISH INSTALLATION-----------------------"
