#!/bin/sh

sxhkd &
setxkbmap -option caps:swapescape
xcompmgr &
hsetroot -solid "#000000"
bspwm_lemonbar &
pidof bspwm_swallow || bspwm_swallow &

xinput set-prop '04CA00B1:00 04CA:00B1 Touchpad' 'libinput Tapping Enabled' 1
xinput set-prop '04CA00B1:00 04CA:00B1 Touchpad' 'libinput Accel Speed' +0.5

bspc config focused_border_color "#9d03fc"
bspc config border_width         5
bspc config normal_border_color  "#706d6d"
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# if desktops 1 and 2 dont exist already, create them.
if [ -z "$(bspc query --desktops --names | grep 1)" ]; then
    bspc monitor --add-desktops 1 
fi
