#!/bin/bash

case "$1" in
    laptop-only)
        bspc monitor "$MONITOR_SECONDARY" -a placeholder
        bspc query -D --names | while read line; do [ "$line" != "placeholder" ] && bspc desktop "$line" -m "$MONITOR_PRIMARY"; done 
        xrandr --output "$MONITOR_SECONDARY" --off
        bspc desktop placeholder --remove
    ;;
    monitor-connected)
        xrandr --output "$MONITOR_SECONDARY" --auto
        xrandr --output "$MONITOR_SECONDARY" --right-of "$MONITOR_PRIMARY"
        ~/.config/polybar/launch_polybar > /dev/null 2>&1
        setxkbmap -option "caps:swapescape"
    ;;
    *) 
        echo "Error: first arg must be laptop-only/monitor-connected"
    ;;
esac
