#!/bin/sh

sxhkd &

#xcompmgr &

setxkbmap -option caps:swapescape

#xss-lock locker slock &

~/.config/polybar/launch_polybar &

#bspc monitor eDP-1 -d 1 2 
#bspc monitor HDMI-1 -d 3 4 5 6 7 8 9 10 "ranger"


ranger_node="$(cat ~/.config/bspwm/ranger_node.txt)"


bspc config focused_border_color "#9d03fc"
#bspc config top_padding -10
#bspc config right_padding -10
#bspc config bottom_padding 20
#bspc config left_padding -10

bspc config border_width         5
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
