#!/bin/bash

case "$1" in
    laptop-only)
        bspc query -D --names | while read line; do bspc desktop "$line" -m eDP-1; done 
        xrandr --output HDMI-1 --off
    ;;
    monitor-connected)
        xrandr --output HDMI-1 --auto
        xrandr --output HDMI-1 --right-of eDP-1
        ~/.config/polybar/launch_polybar > /dev/null 2>&1
        setxkbmap -option "caps:swapescape"
    ;;
    *) 
        echo "Error: first arg must be laptop-only/monitor-connected"
    ;;
esac
