#!/bin/sh

folder=$(echo "home\nschool\nprakashsCommands" | dmenu -p "jump to which folder?" -i)

[ -z "$folder" ] && exit 1 

case $folder in 
    home)
        cd ~/
        ;;
    school)
        cd ~/Documents/School
        ;;
    prakashsCommands)
        cd ~/prakashsCommands
        ;;
esac

folder=$(ls | dmenu -p "Open folder with ranger:" -i)

[ -z "$folder" ] && exit 1 

cd $folder
st -e ranger
